# -*- coding: utf-8 -*-
"""LAB2_116310462007-0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ykG6nqciJMb89w9HFqtJB-TI3RB3Mwun
"""
#=====================================1==========================================
print(2**2**3)
print(2**(2**3))
print((2**2)**3)
#=====================================2==========================================
x = 5
x %= 3
print(x)
#=====================================3==========================================
x = 5
x //= 3
print(x)
#=====================================4==========================================
x = 5
x &= 3
print(x)
#=====================================5==========================================
x = 5
x != 3
print(x)
#=====================================6==========================================
x = 5
x ^= 3
print(x)
#=====================================7==========================================
x = 5
x >>= 3
print(x)
#=====================================8==========================================
x=5
print(x < 3)
print(x > 3)
print(x > 3 and  x < 10)
print(not(x > 3 and x > 10))
#=====================================9==========================================
x = y= 10
print ('{} == {} => {}'.format(x, y, (x ==y)))
print('{} is {} => {}'.format(x, y, (x is y)))
print('{} is not {} => {}'.format(x, y, (x is not y)))
print('id x = {} and id y = {}'.format(id(x), id(y)))
#=====================================10==========================================
x = 10.0
y= float(y)
print ('{} == {} => {}'.format(x, y, (x ==y)))
print('{} is {} => {}'.format(x, y, (x is y)))
print('{} is not {} => {}'.format(x, y, (x is not y)))
print('id x = {} and id y = {}'.format(id(x), id(y)))
#=====================================11==========================================
print('==============Menu==================')
print('1. Add')
print('2. Subtract')
print('3. Multiply')
print('4. Divide')
number_1 = float(input('Enter Number1: '))
number_2 = float(input('Enter Number2: '))
select_input = str(input('Select Choice: '))
if(select_input == '1' ):
  print('Answer is {:.2f} + {:.2f} = {:.2f}'.format(number_1, number_2,(number_1 + number_2)))
elif(select_input == '2'):
  print('Answer is {:.2f} - {:.2f} = {:.2f}'.format(number_1, number_2,(number_1 - number_2)))
elif(select_input == '3'):
  print('Answer is {:.2f} x {:.2f} = {:.2f}'.format(number_1, number_2,(number_1 * number_2)))
elif(select_input == '4' and number_2 != 0):
  print('Answer is {:.2f} / {:.2f} = {:.2f}'.format(number_1, number_2,(number_1 / number_2)))
elif(select_input == '4' and number_2 == 0):
  print('Divide by Zero') 
else:
  print('stupid little shit')