# -*- coding: utf-8 -*-
"""1163104620070-LAB3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S2IjN11iruEWuuLoWqngrrFhPiUwvYVS
"""
import sys

#=====================================1==========================================
print(list (range (1,10)))
print(list (range (1,10,1)))
print(list (range (1,10,2)))
#=====================================2ERROR=====================================
#print(list (range (1,10,0)))
#step is zero
#=====================================3==========================================
print(list (range (10,1,-2)))
#=====================================4==========================================
print(list (range (10,1,1)))
#'''เพราะมันเพิ่มที่ละ1'''
#=====================================5ERROR=====================================
#print(list (range (1,10,0.5)))
#'''เพราะstepเป็นfloatไม่ได้'''
#=====================================6==========================================
print(list(range(1,10,2)))
print(list(range(10,1,-2)))
#=====================================7==========================================
while True :
  mutiNum = input('Enter Number : ')
  if mutiNum == 'END' :
    break
  else :
     try :
      mutiNum = int(mutiNum)
      for i in range(1,13,1):
        print ('{} x{} = {}'.format(mutiNum,i,mutiNum*i))
     except ValueError:
       print("--------it's not intiger ,monkey------")


#=====================================8==========================================
while True :
  Enter = input('enter Number :')
  if Enter == 'Exit'  :
    break
  else :
    try : 
      Enter = int(Enter)
      word = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
      if Enter > 26 :
        continue
      for row in range(1,Enter+1) :
        print(word[row-1]*row)
    except ValueError:
      print("--------it's not intiger ,monkey------")
      
#=====================================9==========================================
while True :
  Newpassword = input('Enter new password (max 8) :')
  if len(Newpassword) > 8 :
    print(" that too much stupid")
    continue
  else :
    for i in range(1,4):
      password = input('{} Enter password:'.format(i))
      if password == Newpassword :
        print('password correct!!!')
        break
      else:
        print('password not correct!!!')
        if i == 3:
          print('close proram')
          sys.exit()