# -*- coding: utf-8 -*-
"""1163104620070-LAB4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-3ie9ulM0pf7-dk5cKt5jiuM7El2_P6R
"""

def result(score):
  sum = score[0]+score[1]+score[2]
  sum = sum/230
  sum = sum*100
  sum = sum
  return sum 
def max(data,position):
  local_Ram = []
  for i in range(len(data)):
    a  = data[i+1][position]
    local_Ram.append(a)
  local_Ram.sort()
  return(local_Ram[-1])
def min(data,position):
  local_Ram = []
  for i in range(len(data)):
    a  = data[i+1][position]
    local_Ram.append(a)
  local_Ram.sort()
  return(local_Ram[0])
def avg(data,position):
  local_Ram = []
  for i in range(len(data)):
    a  = data[i+1][position]
    local_Ram.append(a)
  return sum(local_Ram) / len(local_Ram)
def display(data):
  all_Result = []
  print('=======================================================================================================')
  print('No .                 Mid                    Fin                       Lab                     Result')
  print('=======================================================================================================')
  for stu_no in range(len(data)):
    print(f'Student{stu_no+1}{data[stu_no+1][0]:14}{data[stu_no+1][1]:24}{data[stu_no+1][2]:28}{data[stu_no+1][3]:28}')
    all_Result.append(result(data[stu_no+1]))
  print('=======================================================================================================')
  print(f'Max    {max(data,0):15}{max(data,1):24}{max(data,2):28}{max(data,3):28}')
  print(f'Min    {min(data,0):15}{min(data,1):24}{min(data,2):28}{min(data,3):28}')
  print(f'Avg    {avg(data,0):15}{avg(data,1):24}{avg(data,2):28}{avg(data,3):28}')
  print('=======================================================================================================')
  for stu_no in range(len(data)):
    word = '**********'
    Ram = data[stu_no+1][3] // 10
    print(f'Student {stu_no+1} {data[stu_no+1][3]} {word[0:int(Ram)]}')
data = {}
num_Student = int(input('Enter number of students : '))
for x in range(num_Student):
  print('Enter Score of Student ',x+1)
  Mid = input('Mid :')
  Final = input('Final :')
  Lab = input('Lab :')
  all_Score = ([int(Mid),int(Final),int(Lab)])
  data[int(x+1)] =  all_Score 
  data[int(x+1)].append(result(all_Score))
display(data)