# -*- coding: utf-8 -*-
"""lab6_116310462007-0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uI75zhAQ4EX1ydic08XEaaGPtVu0cLsI
"""
#====================================1=======================================
def f(*args, **kwargs):
 print(args, kwargs)
a = [1, 2]
d = {'x': 3, 'y': 4}

f(a) 
f(*a) 
#f(**a) 
f(d) 
f(*d) 
f(**d) 
f(a, d) 
f(*a, d) 
f(a, **d) 
f(*a, **d)
#========================================2======================================
def circumferene(r):
  sum = 2*(3.14*r)
  return sum
def circlearea(r):
  sum = 3.14*(r*r)
  return sum
def surfacearea(r,h):
  return(circlearea(r)*2)+(circumferene(r)*h)


surfacearea(3,5)
#=========================================3=======================================
thainum = {0:"", 1:"หนึ่ง", 2:"สอง", 3:"สาม",4:"สี่", 5:"ห้า", 6:"หก", 7:"เจ็ด", 8:"แปด", 9:"เก้า"}
thaimulti = { 2: "สิบ", 3:"ร้อย", 4: "พัน", 5:"หมื่น", 6:"แสน", 7:"ล้าน"}
submit = []
def satangCal(num):
    num = str(num)
    for ele in range(len(num)):
        submit.append(thainum[int(num[ele])])
        if len(num)-ele in thaimulti:
            submit.append(thaimulti[len(num)-ele])
    submit.append('สตางค์')
def thaibath(num):
    satang = None
    num = str(num)
    if '.' in num:
        num = num.split('.')
        satang = num.pop(1)
        num = str(num[0])
    for ele in range(len(num)):
        submit.append(thainum[int(num[ele])])
        if len(num)-ele in thaimulti:
            submit.append(thaimulti[len(num)-ele])        
    if len(submit) != 1:
        if submit[-3] == 'สอง':
            submit[-3] = 'ยี่'
        elif submit[-3] == 'หนึ่ง':
            submit.pop(-3)
        if submit[-1] == 'หนึ่ง':
            submit[-1] = 'เอ็ด'
    while '' in submit:
        submit.remove('')  
    if  satang is not None:
        satang = int(satang)
        submit.append('บาท')
        satangCal(satang) 
    elif satang is None:
        submit.append('บาทถ้วน')
    print(''.join(submit))
thaibath(1234.56)