# -*- coding: utf-8 -*-
"""1163104620070-LAB5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RUUWvm7Om8YiISjMIkKLKABd-AOJEM0K
"""
#=======================================1=========================================
fname =  open('D:\git\everything\sw LAB\Lab5\\fileTH.txt','r')
line_count = 0
char_count = 0
for line in fname:
  line_count += 1
  char_count += len(line)
print(line_count,"lines",char_count,"chars")
fname.close
#=======================================2=========================================
fname = open('D:\git\everything\sw LAB\Lab5\\workHours.txt','r')
print('================================================================')
for i in fname:
  id, name, mon, tue, wed, thu, fri = i.split()
  hours = float(mon)+float(tue)+float(wed)+float(thu)+float(fri)
  print(f'{name}  ID:{id}  worker {hours:.2f}  hours  {hours/5:.2f}/day')
print('================================================================')
fname = open('D:\git\everything\sw LAB\Lab5\\workHours.txt','r')
for row in fname: 
  id, name, mon, tue, wed, thu, fri = row.split()
  hours = float(mon)+float(tue)+float(wed)+float(thu)+float(fri)
  print(name+' '+"*"*int(hours))
fname.close()
#=======================================3=========================================

name = input()
fname = open('D:\git\everything\sw LAB\Lab5\\stuScore.txt','r')

writeStart = open(f'{name}','w+') 
writeStart.write('')
write = open(f'{name}','a+')

def grade(data):
  if(data >= 80):return('A')
  elif(data >= 75):return('B+')
  elif(data >= 70):return('B')
  elif(data >= 65):return('C+')
  elif(data >= 60):return('C')
  elif(data >= 55):return('D+')
  elif(data >= 50):return('D')
  elif(data < 50):return('F')
count = 0
dik = {'A':0,'B+':0,'B':0,'C+':0,'C':0,'D+':0,'D':0,'F':0}
print('================================================================')
for i in fname:
  count += 1
  id, name, mid, final, lab = i.split()
  sum = float(mid)+float(mid)+float(lab)
  if(grade(sum) == 'A'):dik['A'] += 1
  elif(grade(sum) == 'B+'):dik['B+'] += 1
  elif(grade(sum) == 'B'):dik['B'] += 1
  elif(grade(sum) == 'C+'):dik['C+'] += 1
  elif(grade(sum) == 'C'):dik['C'] += 1
  elif(grade(sum) == 'D+'):dik['D+'] += 1
  elif(grade(sum) == 'D'):dik['D'] += 1
  elif(grade(sum) == 'F'):dik['F'] += 1
  ok = f'{id}  {name}  {float(mid):.2f}  {float(final):.2f}  {float(lab):.2f}  {str(grade(sum))}'
  print(ok)
  write.write(f'{id}  {name}  {float(mid):.2f}  {float(final):.2f}  {float(lab):.2f}  {str(grade(sum))}\n')
print('================================================================')
print(f'COUNT = {count}\n')
write.write(f'COUNT = {count}')
for key,value in dik.items():
  write.write(f'{key} = {value}\n')
  print(key,' = ', value)
write.close()
writeStart.close()